name: Build release binaries
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "46 5 7 * *" # At 05:46 on day-of-month 1 in every 3rd month from January through December

jobs:
  build-rust:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust_target: [x86_64-unknown-linux-gnu]
        # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2004-Readme.md
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3
      - run: find .github
        shell: bash
      - uses: ./.github/setupandbuild
        with:
          rust_target: ${{ matrix.rust_target }}
      - name: Strip binary
        if: matrix.rust_target == 'x86_64-unknown-linux-musl'
        run: |
          strip output_dir/pg2parquet
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ matrix.rust_target }}
          path: output_dir/pg2parquet${{ matrix.rust_target == 'x86_64-pc-windows-gnu' && '.exe' || '' }}
